info.onLifeZero(function () {
    game.gameOver(false)
})
controller.player2.onEvent(ControllerEvent.Connected, function () {
    CHASSER.setPosition(-1, -3)
    CHASSER.follow(myCorg, 0)
    controller.player2.moveSprite(PLAYER_HUNTER, 30, 30)
    PLAYER_HUNTER.setPosition(34, 11)
    scene.setBackgroundImage(assets.image`cave backround`)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    music.play(music.melodyPlayable(music.wawawawaa), music.PlaybackMode.UntilDone)
})
let PLAYER_HUNTER: Sprite = null
let CHASSER: Sprite = null
let myCorg: Corgio = null
myCorg = corgio.create(SpriteKind.Player)
CHASSER = sprites.create(img`
    . . . . . . . . . . b 5 b . . . 
    . . . . . . . . . b 5 b . . . . 
    . . . . . . . . . b c . . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b f f 5 5 5 b . . . 
    . . . . b b 5 d 1 f 5 5 d f . . 
    . . . . b 5 5 1 f f 5 d 4 c . . 
    . . . . b 5 5 d f b d d 4 4 . . 
    b d d d b b d 5 5 5 4 4 4 4 4 b 
    b b d 5 5 5 b 5 5 4 4 4 4 4 b . 
    b d c 5 5 5 5 d 5 5 5 5 5 b . . 
    c d d c d 5 5 b 5 5 5 5 5 5 b . 
    c b d d c c b 5 5 5 5 5 5 5 b . 
    . c d d d d d d 5 5 5 5 5 d b . 
    . . c b d d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `, SpriteKind.Enemy)
PLAYER_HUNTER = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf2222f4e...........
    fbbbbf2222fd4...........
    .fccf45544f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
scene.setBackgroundImage(assets.image`forest backround`)
myCorg.updateSprite()
myCorg.verticalMovement()
myCorg.horizontalMovement()
myCorg.cameraFollow()
tiles.setCurrentTilemap(tilemap`level2`)
info.setLife(1)
CHASSER.setPosition(6, 7)
CHASSER.follow(myCorg, 60)
PLAYER_HUNTER.setPosition(2, 3)
